# -*- coding: utf-8 -*-
"""charts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h6sxksOplZwUpmTKiU1CDPkucgEv0VBG
"""

import pandas as pd

import json

data = json.load(open('output.json'))

scenarios = []
content = {}
only_react_scenarios = []

for key in data["averages"]:
  if(key[0]=='r'): 
    only_react_scenarios.append(key)
  
  scenarios.append(key)
  for subkey in data["averages"][key]:
    if subkey in content:
        content[subkey].append(data["averages"][key][subkey]["avg"])
    else:
        content[subkey] = [data["averages"][key][subkey]["avg"]]


print(content)

import plotly.graph_objects as go

colors = ["#ED4974", "#8958D3", "#16B9E1","#58DE7B", "#F0D864","#FF8057"] 

# import plotly.express as px
# print(px.data.tips())
for key in content:
  if(key != 'Highest CPU (JS thread)%'):
    fig = go.Figure(data=[go.Bar(
        x=scenarios,
        y=content[key],
        marker_color=colors # marker color can be a single color value or an iterable
    )])
    fig.update_layout(title_text=key)

    # fig = px.bar(y=content[key] , x=scenarios, title=key, color="red")
    fig.show()
  else:
    fig = go.Figure(data=[go.Bar(
        x=only_react_scenarios,
        y=content[key],
        marker_color=colors # marker color can be a single color value or an iterable
    )])
    fig.update_layout(title_text=key)

    # fig = px.bar(y=content[key] , x=only_react_scenarios, title=key)
    fig.show()



